### PR TITLE
(svprimlit-update): Updating current SvPrimLit implementation

### PR DESCRIPTION
**Pull request by vasilissoti**

### CODE REVIEW

**Comment by DaveMcEwan** [comment]
Do you think this PR covers #41 completely?

**Comment by vasilissoti** [comment]
I can see that both YAML and JSON files include "comment" in their contents and I figured out that bug occurred do to the absence of comment from the display trait.

**Comment by vasilissoti** [comment]
All the necessary updates have been implemented. The new project organisation will be implemented in separate PRs.

**Comment by vasilissoti** [comment]
Ready to be merged.

**Pull request merged**
