### PR TITLE
(svprimlit-cmp): Updating partial_cmp and eq

### PR DESCRIPTION
**Pull request by vasilissoti**

### CODE REVIEW

**Comment by vasilissoti** [comment]
After testing the behaviour of Cadence Xcelium 20.09 the following conclusion was made:

A comparison between a 4-state sized (and based) integral that contains either a high impedance/unknown value with another integral returns an unknown value x.

The implementation that is followed in SvPrimaryLiteralIntegral is equivalent. More specifically, a partial_cmp between a an integral that contains X/Z(s) and another integral returns None and therefore lt,gt,le,ge all will return false. 

As far as the partial eq is concerned, if any of the two integrals contains X/Z(s) then instead of directly returning false, the implementation checks whether there is a full equivalence (1 to 1 match). This enables the execution of assertions in the rs files instead of letting all the 4-state integrals that contain X/Z(s) fail. Moreover the semantic equivalence used for 2-state/4-state with noX/Z(s) cannot be applied in this case since _minimum_width does not support 4-state integrals with X/Z(s).

**Comment by DaveMcEwan** [comment]
Can you make sure the testcases contain assertions please.
That will be a bit nicer than relying on the Display trait.

**Comment by vasilissoti** [comment]
Yes of course. Up to now I had assertions to non-boolean test cases. I will add assertions to all the boolean test cases as well.

**Comment by vasilissoti** [comment]
> Can you make sure the testcases contain assertions please.
> That will be a bit nicer than relying on the Display trait.

Fixed.

**Comment by vasilissoti** [comment]
All the required implementation updates have been made and this PR is ready to be merged.

Pending: Addition of extra traits (will be implemented in a separate PR)

**Comment by vasilissoti** [comment]
New changes need to be made. Turning again into draft.

**Comment by vasilissoti** [comment]
The commits of this PR are included in svprimlit-traits PR. This PR will be closed and any modifications will be made in svprimlit-traits.

**Pull request closed without merging**
